# Setup
title: HUFS IVC Lab
description: |
  지능형 시각적 계산 연구실
  Intelligent Visual Computing Laboratory
url: https://hufsivclab.github.io/
paginate: 5
permalink: pretty
cover_image: /black.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
#twitter:
#  username: vszhub
#  card: summary
logo: logo.png
social:
  name: Yunjoo OH
  links:
    - mailto:bkim@hufs.ac.kr
    - https://github.com/hufsivclab
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Yunjoo OH
  url: https://github.com/Oyunjoo
  email: yunju7890@hufs.ac.kr
